button_option: stbc_
comments: 0
late_load: 0
location: content
node_types:
  blog: blog
  article: null
  page: null
  test: null
option_extras:
  'Google Plus One:plusone': 'Google Plus One:plusone'
  'Facebook Like:fblike': 'Facebook Like:fblike'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '"Facebook:facebook","Tweet:twitter","LinkedIn:linkedin","Email:email","ShareThis:sharethis","Pinterest:pinterest"'
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  blog:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  test:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-cc23c94a-23-9798-a9f2-f25080e2db66
callesi: '0'
